# Generated by Django 4.0.10 on 2025-01-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person_email',
            field=models.EmailField(max_length=254, verbose_name='Контактный емейл'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person_name',
            field=models.CharField(max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person_phone',
            field=models.CharField(max_length=255, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Введите наименование клиента (Организация или ФИО если заказчик физ. лицо)', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_email',
            field=models.EmailField(max_length=254, verbose_name='Контактный емейл'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_name',
            field=models.CharField(max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_phone',
            field=models.CharField(max_length=255, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_operator',
            field=models.BooleanField(default=True, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Введите наименование заказчика (Оператор или обслуживающая компания)', max_length=255, verbose_name='Наименование'),
        ),
    ]
