# Generated by Django 4.0.10 on 2025-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_invoiced',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('В работе', 'in_work'), ('Завершена', 'done'), ('Выставлены документы', 'invoiced'), ('Оплачена', 'paid'), ('Отменена', 'canceled')], default='in_work', max_length=50, verbose_name='Статус'),
        ),
    ]
